services:
  php:
    build: docker/php
    working_dir: /application
    volumes:
      - .:/application
    environment:
      - PHP_OPCACHE_ENABLE=1
      - PHP_OPCACHE_ENABLE_CLI=1

  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - .:/application
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  mysql:
    image: mysql:lts
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: laravel
      PMA_PASSWORD: laravel
    depends_on:
      - mysql

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - "8025:8025"

volumes:
  mysql-data:
